spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb-service:3306/scdf
    username: root
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  batch:
    jdbc:
      initialize-schema: ALWAYS
      isolation-level-for-create: default

  kafka:
    producer:
      bootstrap-servers: kafka-broker.kafka:9092
    consumer:
      bootstrap-servers: kafka-broker.kafka:9092
    bootstrap-servers: kafka-broker.kafka:9092